package:
  name: host-guest
  version: !!str dev


requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - mdtraj-dev
    - openmm    
    - ambermini

  run:
    - python
    - pandas
    - scipy
    - mdtraj-dev
    - openmm    
    - ambermini    

about:
  home: https://github.com/choderalab/host-guest
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

